#!/usr/bin/env python3
"""
gen_sweep_list.py — pick the read-only commands the sweeper may issue.

hulk is a shared machine. Other people's jobs run on these GPUs. The sweeper
must not change GPU state, so this filter is deliberately conservative: a
command is admitted only if it is positively identified as a read, and it is
rejected if it contains any token that suggests a write, a reset, or an
allocation — even when the name also contains GET.

Admitted:
  - class 0x0000 (NV01_ROOT), 0x0080 (NV01_DEVICE_0), 0x2080 (NV20_SUBDEVICE_0)
    Those are the three objects sweep_controls.c builds.
  - name contains GET, QUERY, READ, or INFO
  - a params struct size is known from the headers

Rejected (any match wins):
  - SET / WRITE / ALLOC / FREE / RESET / CLEAR / DISABLE / ENABLE / INJECT /
    FLUSH / RELEASE / ACQUIRE / BIND / UNBIND / ATTACH / DETACH / START / STOP /
    UPDATE / MODIFY / CTRL_CMD_..._CONTROL / EXEC / SUBMIT / TRIGGER / RECOVER /
    SHUTDOWN / POWER / SERVICE / NOTIFY / EVENT / SCHEDULE
  - _INTERNAL_ (GSP-internal; not reachable from an unprivileged client and
    riskier if it is)
  - size 0 or size unknown

Usage:
    python3 tools/effectmap/gen_sweep_list.py \
        --table tools/effectmap/out/ctrl_table.json \
        --out   tools/effectmap/out/sweep_cmds.txt
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# The three objects the sweeper actually holds.
ALLOWED_CLASSES = {"0x0000", "0x0080", "0x2080"}

# A name must contain one of these to be considered a read.
# _DESCRIBE added 2026-07-30: NV2080_CTRL_CMD_GPU_DESCRIBE_PARTITIONS is a pure
# read (is_set=False, is_internal=False, confirmed against kernel_mig_manager.c
# — kmigmgrDescribeGPUInstances_IMPL has no pRmApi->Control call anywhere in its
# body, served from a cache populated at MIG-enable time) but was falling
# through as "not_a_read" on name alone. See control-folder/plans/
# mig-command-classification.md §2 Pattern E.
READ_TOKENS = ("_GET", "_QUERY", "_READ", "_INFO", "_DESCRIBE")

# Any of these disqualifies the command, even if it also looks like a read.
DENY_TOKENS = (
    "_SET", "_WRITE", "_ALLOC", "_FREE", "_RESET", "_CLEAR", "_DISABLE",
    "_ENABLE", "_INJECT", "_FLUSH", "_RELEASE", "_ACQUIRE", "_BIND",
    "_UNBIND", "_ATTACH", "_DETACH", "_START", "_STOP", "_UPDATE",
    "_MODIFY", "_EXEC", "_SUBMIT", "_TRIGGER", "_RECOVER", "_SHUTDOWN",
    "_POWER", "_SERVICE", "_NOTIFY", "_EVENT", "_SCHEDULE", "_INTERNAL_",
    "_CTRL_CMD_RC_", "_MASTER", "_LOCK", "_UNLOCK", "_INIT", "_DESTROY",
    "_REMOVE", "_ADD", "_INSTALL", "_PROGRAM", "_CALIBRAT", "_TEST",
    "_FUZZ", "_DEBUG", "_BREAKPOINT", "_SUSPEND", "_RESUME", "_MIGRAT",
    "_EVICT", "_PROMOTE", "_DEMOTE", "_ZBC", "_PMU_", "_SPDM", "_UCODE",
)


def classify(row: dict) -> tuple[bool, str]:
    """Return (admit, reason)."""
    name = row["name"]
    if row["class_hex"] not in ALLOWED_CLASSES:
        return False, "class_not_held"
    if row["params_size"] is None:
        return False, "size_unknown"
    if row["params_size"] == 0:
        return False, "size_zero"
    for tok in DENY_TOKENS:
        if tok in name:
            return False, f"deny:{tok}"
    if not any(tok in name for tok in READ_TOKENS):
        return False, "not_a_read"
    return True, "ok"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--table", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--report", type=Path, default=None,
                    help="optional JSON of admitted+rejected with reasons")
    args = ap.parse_args()

    doc = json.loads(args.table.read_text(encoding="utf-8"))
    rows = doc["commands"]

    admitted, rejected = [], []
    for r in rows:
        ok, why = classify(r)
        (admitted if ok else rejected).append({**r, "_reason": why})

    admitted.sort(key=lambda r: r["cmd"])

    lines = [
        "# Generated by gen_sweep_list.py — read-only RM control commands.",
        f"# source table: {args.table}",
        f"# admitted {len(admitted)} of {len(rows)}",
        "# format: <cmd_hex> <paramsSize>",
    ]
    for r in admitted:
        lines.append(f"{r['cmd_hex']} {r['params_size']}    # {r['name']}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    by_class: dict[str, int] = {}
    for r in admitted:
        by_class[r["class_hex"]] = by_class.get(r["class_hex"], 0) + 1

    print(f"[gen] admitted {len(admitted)} / {len(rows)}")
    for k in sorted(by_class):
        print(f"[gen]   class {k}: {by_class[k]}")
    print(f"[gen] wrote {args.out}")

    if args.report:
        args.report.write_text(
            json.dumps({"admitted": admitted, "rejected": rejected}, indent=1),
            encoding="utf-8",
        )
        print(f"[gen] wrote {args.report}")


if __name__ == "__main__":
    main()
