#!/usr/bin/env python3
"""
gen_scan_list.py — emit the full command list for `sweep_controls --size-scan`.

CLAUDE.md used to say "see LOG.md for the one-liner that emits all_scan.txt".
That one-liner was never written down, so the first stage of the pipeline was
not reproducible. This is that step, as a script.

The size scan ignores the declared size — it scans upward until the driver
stops answering NV_ERR_INVALID_ARGUMENT — so the second column is a placeholder
and only the command word matters. It is emitted anyway because
`sweep_controls.c:load_cmds` requires two fields per line.

Every command in the table is included, including writes. That is safe: the
scan uses a bogus hObject, so the size check at control.c:450 answers before
object resolution at line 516 and the handler never runs. See CLAUDE.md design
decision 3.

Usage:
    python3 tools/effectmap/gen_scan_list.py \
        --table tools/effectmap/out/ctrl_table.json \
        --out   tools/effectmap/out/all_scan.txt
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--table", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    rows = json.loads(args.table.read_text(encoding="utf-8"))["commands"]

    lines = [
        "# Generated by gen_scan_list.py — every control command, for --size-scan.",
        f"# source table: {args.table}",
        f"# commands: {len(rows)}",
        "# format: <cmd_hex> <placeholder size, ignored by --size-scan>",
    ]
    lines += [f"{r['cmd_hex']} 0    # {r['name']}" for r in rows]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[scan-list] wrote {len(rows)} commands -> {args.out}")


if __name__ == "__main__":
    main()
